
  ktor:
    deployment:
      port: 8080
    application:
      modules:
        - com.example.ApplicationKt.module
    database:
      centralDatabase:
        driver: org.postgresql.Driver
        url: "jdbc:postgresql://192.168.1.20:5432/central_db"
        user: "postgres"
        password: "Giorgos13"
